### PR TITLE
added close button to stream view

### PR DESCRIPTION
**Pull request by lipmem**
Hi,
I've added a simple close button, which brings you back to the index.html.

### CODE REVIEW

**Review by hayzamjs — CHANGES_REQUESTED** [review]
But even if the user clicks on the button torrent-stream continues to stream the previous torrent, we need to find a way to stop the stream and then return to homepage, thanks for the commit though!

**Comment by lipmem** [comment]
Ah ok, I'll look into this

**Comment by lipmem** [comment]
I think my second commit should fix it

**Review by hayzamjs — APPROVED** [review]

**Comment by hayzamjs** [comment]
Good work @Liptoon, thanks a lot! :)

**Pull request merged**
